//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from StaadParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="StaadParserParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IStaadParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] StaadParserParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unitsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnitsSection([NotNull] StaadParserParser.UnitsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pointsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointsSection([NotNull] StaadParserParser.PointsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>frameElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrameElementsSection([NotNull] StaadParserParser.FrameElementsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>areaElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAreaElementsSection([NotNull] StaadParserParser.AreaElementsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>materialSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterialSection([NotNull] StaadParserParser.MaterialSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>areaElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAreaElementsSectionsSection([NotNull] StaadParserParser.AreaElementsSectionsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>frameElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrameElementsSectionsSection([NotNull] StaadParserParser.FrameElementsSectionsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>materialAssignmentSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterialAssignmentSection([NotNull] StaadParserParser.MaterialAssignmentSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boundaryConditionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundaryConditionsSection([NotNull] StaadParserParser.BoundaryConditionsSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loadCaseSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadCaseSection([NotNull] StaadParserParser.LoadCaseSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loadComboSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadComboSection([NotNull] StaadParserParser.LoadComboSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther([NotNull] StaadParserParser.OtherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.load_inner_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoad_inner_section([NotNull] StaadParserParser.Load_inner_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.joint_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoint_load_section([NotNull] StaadParserParser.Joint_load_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.element_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_load_section([NotNull] StaadParserParser.Element_load_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.member_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_load_section([NotNull] StaadParserParser.Member_load_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.joint_load_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoint_load_row([NotNull] StaadParserParser.Joint_load_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.newline_or_white_space"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewline_or_white_space([NotNull] StaadParserParser.Newline_or_white_spaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.generic_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_row([NotNull] StaadParserParser.Generic_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.material_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterial_definition([NotNull] StaadParserParser.Material_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.material_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterial_property([NotNull] StaadParserParser.Material_propertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_section_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSemi_colon_separated_section_content([NotNull] StaadParserParser.Semi_colon_separated_section_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSemi_colon_separated_row([NotNull] StaadParserParser.Semi_colon_separated_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.material_assignment_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterial_assignment_row([NotNull] StaadParserParser.Material_assignment_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.material_assignment_row_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterial_assignment_row_value([NotNull] StaadParserParser.Material_assignment_row_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.section_definition_section_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSection_definition_section_content([NotNull] StaadParserParser.Section_definition_section_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.section_definition_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSection_definition_row([NotNull] StaadParserParser.Section_definition_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.assignment_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_definition([NotNull] StaadParserParser.Assignment_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.load_combination_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoad_combination_row([NotNull] StaadParserParser.Load_combination_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.load_combination_row_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoad_combination_row_data([NotNull] StaadParserParser.Load_combination_row_dataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdDefinitionList</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdDefinitionList([NotNull] StaadParserParser.IdDefinitionListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntigerId</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntigerId([NotNull] StaadParserParser.IntigerIdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RangeOfIds</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeOfIds([NotNull] StaadParserParser.RangeOfIdsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] StaadParserParser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StaadParserParser.row_data_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_data_separator([NotNull] StaadParserParser.Row_data_separatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LoadHeaderData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadHeaderData([NotNull] StaadParserParser.LoadHeaderDataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntigerData([NotNull] StaadParserParser.IntigerDataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleData([NotNull] StaadParserParser.DoubleDataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextData([NotNull] StaadParserParser.TextDataContext context);
}
