//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from StaadParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="StaadParserParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IStaadParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] StaadParserParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] StaadParserParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unitsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitsSection([NotNull] StaadParserParser.UnitsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unitsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitsSection([NotNull] StaadParserParser.UnitsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>pointsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointsSection([NotNull] StaadParserParser.PointsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>pointsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointsSection([NotNull] StaadParserParser.PointsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>frameElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrameElementsSection([NotNull] StaadParserParser.FrameElementsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>frameElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrameElementsSection([NotNull] StaadParserParser.FrameElementsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>areaElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAreaElementsSection([NotNull] StaadParserParser.AreaElementsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>areaElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAreaElementsSection([NotNull] StaadParserParser.AreaElementsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>materialSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterialSection([NotNull] StaadParserParser.MaterialSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>materialSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterialSection([NotNull] StaadParserParser.MaterialSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>areaElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAreaElementsSectionsSection([NotNull] StaadParserParser.AreaElementsSectionsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>areaElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAreaElementsSectionsSection([NotNull] StaadParserParser.AreaElementsSectionsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>frameElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrameElementsSectionsSection([NotNull] StaadParserParser.FrameElementsSectionsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>frameElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrameElementsSectionsSection([NotNull] StaadParserParser.FrameElementsSectionsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>materialAssignmentSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterialAssignmentSection([NotNull] StaadParserParser.MaterialAssignmentSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>materialAssignmentSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterialAssignmentSection([NotNull] StaadParserParser.MaterialAssignmentSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boundaryConditionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoundaryConditionsSection([NotNull] StaadParserParser.BoundaryConditionsSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boundaryConditionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoundaryConditionsSection([NotNull] StaadParserParser.BoundaryConditionsSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>loadCaseSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoadCaseSection([NotNull] StaadParserParser.LoadCaseSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>loadCaseSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoadCaseSection([NotNull] StaadParserParser.LoadCaseSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>loadComboSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoadComboSection([NotNull] StaadParserParser.LoadComboSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>loadComboSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoadComboSection([NotNull] StaadParserParser.LoadComboSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOther([NotNull] StaadParserParser.OtherContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOther([NotNull] StaadParserParser.OtherContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.load_inner_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoad_inner_section([NotNull] StaadParserParser.Load_inner_sectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.load_inner_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoad_inner_section([NotNull] StaadParserParser.Load_inner_sectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.joint_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoint_load_section([NotNull] StaadParserParser.Joint_load_sectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.joint_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoint_load_section([NotNull] StaadParserParser.Joint_load_sectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.element_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement_load_section([NotNull] StaadParserParser.Element_load_sectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.element_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement_load_section([NotNull] StaadParserParser.Element_load_sectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.member_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_load_section([NotNull] StaadParserParser.Member_load_sectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.member_load_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_load_section([NotNull] StaadParserParser.Member_load_sectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.joint_load_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoint_load_row([NotNull] StaadParserParser.Joint_load_rowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.joint_load_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoint_load_row([NotNull] StaadParserParser.Joint_load_rowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.newline_or_white_space"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewline_or_white_space([NotNull] StaadParserParser.Newline_or_white_spaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.newline_or_white_space"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewline_or_white_space([NotNull] StaadParserParser.Newline_or_white_spaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.generic_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_row([NotNull] StaadParserParser.Generic_rowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.generic_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_row([NotNull] StaadParserParser.Generic_rowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterial_definition([NotNull] StaadParserParser.Material_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterial_definition([NotNull] StaadParserParser.Material_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterial_property([NotNull] StaadParserParser.Material_propertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterial_property([NotNull] StaadParserParser.Material_propertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_section_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSemi_colon_separated_section_content([NotNull] StaadParserParser.Semi_colon_separated_section_contentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_section_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSemi_colon_separated_section_content([NotNull] StaadParserParser.Semi_colon_separated_section_contentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSemi_colon_separated_row([NotNull] StaadParserParser.Semi_colon_separated_rowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSemi_colon_separated_row([NotNull] StaadParserParser.Semi_colon_separated_rowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_assignment_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterial_assignment_row([NotNull] StaadParserParser.Material_assignment_rowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_assignment_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterial_assignment_row([NotNull] StaadParserParser.Material_assignment_rowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_assignment_row_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaterial_assignment_row_value([NotNull] StaadParserParser.Material_assignment_row_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_assignment_row_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaterial_assignment_row_value([NotNull] StaadParserParser.Material_assignment_row_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.section_definition_section_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSection_definition_section_content([NotNull] StaadParserParser.Section_definition_section_contentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.section_definition_section_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSection_definition_section_content([NotNull] StaadParserParser.Section_definition_section_contentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.section_definition_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSection_definition_row([NotNull] StaadParserParser.Section_definition_rowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.section_definition_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSection_definition_row([NotNull] StaadParserParser.Section_definition_rowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.assignment_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_definition([NotNull] StaadParserParser.Assignment_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.assignment_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_definition([NotNull] StaadParserParser.Assignment_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.load_combination_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoad_combination_row([NotNull] StaadParserParser.Load_combination_rowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.load_combination_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoad_combination_row([NotNull] StaadParserParser.Load_combination_rowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.load_combination_row_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoad_combination_row_data([NotNull] StaadParserParser.Load_combination_row_dataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.load_combination_row_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoad_combination_row_data([NotNull] StaadParserParser.Load_combination_row_dataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdDefinitionList</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdDefinitionList([NotNull] StaadParserParser.IdDefinitionListContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdDefinitionList</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdDefinitionList([NotNull] StaadParserParser.IdDefinitionListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntigerId</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntigerId([NotNull] StaadParserParser.IntigerIdContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntigerId</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntigerId([NotNull] StaadParserParser.IntigerIdContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RangeOfIds</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeOfIds([NotNull] StaadParserParser.RangeOfIdsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RangeOfIds</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeOfIds([NotNull] StaadParserParser.RangeOfIdsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] StaadParserParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] StaadParserParser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.row_data_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRow_data_separator([NotNull] StaadParserParser.Row_data_separatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.row_data_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRow_data_separator([NotNull] StaadParserParser.Row_data_separatorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LoadHeaderData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoadHeaderData([NotNull] StaadParserParser.LoadHeaderDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LoadHeaderData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoadHeaderData([NotNull] StaadParserParser.LoadHeaderDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntigerData([NotNull] StaadParserParser.IntigerDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntigerData([NotNull] StaadParserParser.IntigerDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleData([NotNull] StaadParserParser.DoubleDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleData([NotNull] StaadParserParser.DoubleDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextData([NotNull] StaadParserParser.TextDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextData([NotNull] StaadParserParser.TextDataContext context);
}
