//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from StaadParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IStaadParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class StaadParserBaseListener : IStaadParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] StaadParserParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] StaadParserParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unitsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitsSection([NotNull] StaadParserParser.UnitsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unitsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitsSection([NotNull] StaadParserParser.UnitsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>pointsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointsSection([NotNull] StaadParserParser.PointsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>pointsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointsSection([NotNull] StaadParserParser.PointsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>frameElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameElementsSection([NotNull] StaadParserParser.FrameElementsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>frameElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameElementsSection([NotNull] StaadParserParser.FrameElementsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>areaElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAreaElementsSection([NotNull] StaadParserParser.AreaElementsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>areaElementsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAreaElementsSection([NotNull] StaadParserParser.AreaElementsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>materialSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterialSection([NotNull] StaadParserParser.MaterialSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>materialSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterialSection([NotNull] StaadParserParser.MaterialSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>areaElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAreaElementsSectionsSection([NotNull] StaadParserParser.AreaElementsSectionsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>areaElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAreaElementsSectionsSection([NotNull] StaadParserParser.AreaElementsSectionsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>frameElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameElementsSectionsSection([NotNull] StaadParserParser.FrameElementsSectionsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>frameElementsSectionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameElementsSectionsSection([NotNull] StaadParserParser.FrameElementsSectionsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>materialAssignmentSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterialAssignmentSection([NotNull] StaadParserParser.MaterialAssignmentSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>materialAssignmentSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterialAssignmentSection([NotNull] StaadParserParser.MaterialAssignmentSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boundaryConditionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoundaryConditionsSection([NotNull] StaadParserParser.BoundaryConditionsSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boundaryConditionsSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoundaryConditionsSection([NotNull] StaadParserParser.BoundaryConditionsSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loadCaseSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadCaseSection([NotNull] StaadParserParser.LoadCaseSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loadCaseSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadCaseSection([NotNull] StaadParserParser.LoadCaseSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loadComboSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadComboSection([NotNull] StaadParserParser.LoadComboSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loadComboSection</c>
	/// labeled alternative in <see cref="StaadParserParser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadComboSection([NotNull] StaadParserParser.LoadComboSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther([NotNull] StaadParserParser.OtherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther([NotNull] StaadParserParser.OtherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.load_inner_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad_inner_section([NotNull] StaadParserParser.Load_inner_sectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.load_inner_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad_inner_section([NotNull] StaadParserParser.Load_inner_sectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.joint_load_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoint_load_section([NotNull] StaadParserParser.Joint_load_sectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.joint_load_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoint_load_section([NotNull] StaadParserParser.Joint_load_sectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.element_load_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_load_section([NotNull] StaadParserParser.Element_load_sectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.element_load_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_load_section([NotNull] StaadParserParser.Element_load_sectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.member_load_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_load_section([NotNull] StaadParserParser.Member_load_sectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.member_load_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_load_section([NotNull] StaadParserParser.Member_load_sectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.joint_load_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoint_load_row([NotNull] StaadParserParser.Joint_load_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.joint_load_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoint_load_row([NotNull] StaadParserParser.Joint_load_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.newline_or_white_space"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewline_or_white_space([NotNull] StaadParserParser.Newline_or_white_spaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.newline_or_white_space"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewline_or_white_space([NotNull] StaadParserParser.Newline_or_white_spaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.generic_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_row([NotNull] StaadParserParser.Generic_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.generic_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_row([NotNull] StaadParserParser.Generic_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterial_definition([NotNull] StaadParserParser.Material_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterial_definition([NotNull] StaadParserParser.Material_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterial_property([NotNull] StaadParserParser.Material_propertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterial_property([NotNull] StaadParserParser.Material_propertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_section_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSemi_colon_separated_section_content([NotNull] StaadParserParser.Semi_colon_separated_section_contentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_section_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSemi_colon_separated_section_content([NotNull] StaadParserParser.Semi_colon_separated_section_contentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSemi_colon_separated_row([NotNull] StaadParserParser.Semi_colon_separated_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.semi_colon_separated_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSemi_colon_separated_row([NotNull] StaadParserParser.Semi_colon_separated_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_assignment_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterial_assignment_row([NotNull] StaadParserParser.Material_assignment_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_assignment_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterial_assignment_row([NotNull] StaadParserParser.Material_assignment_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.material_assignment_row_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterial_assignment_row_value([NotNull] StaadParserParser.Material_assignment_row_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.material_assignment_row_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterial_assignment_row_value([NotNull] StaadParserParser.Material_assignment_row_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.section_definition_section_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSection_definition_section_content([NotNull] StaadParserParser.Section_definition_section_contentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.section_definition_section_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSection_definition_section_content([NotNull] StaadParserParser.Section_definition_section_contentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.section_definition_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSection_definition_row([NotNull] StaadParserParser.Section_definition_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.section_definition_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSection_definition_row([NotNull] StaadParserParser.Section_definition_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.assignment_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_definition([NotNull] StaadParserParser.Assignment_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.assignment_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_definition([NotNull] StaadParserParser.Assignment_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.load_combination_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad_combination_row([NotNull] StaadParserParser.Load_combination_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.load_combination_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad_combination_row([NotNull] StaadParserParser.Load_combination_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.load_combination_row_data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad_combination_row_data([NotNull] StaadParserParser.Load_combination_row_dataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.load_combination_row_data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad_combination_row_data([NotNull] StaadParserParser.Load_combination_row_dataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdDefinitionList</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdDefinitionList([NotNull] StaadParserParser.IdDefinitionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdDefinitionList</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdDefinitionList([NotNull] StaadParserParser.IdDefinitionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntigerId</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntigerId([NotNull] StaadParserParser.IntigerIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntigerId</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntigerId([NotNull] StaadParserParser.IntigerIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RangeOfIds</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangeOfIds([NotNull] StaadParserParser.RangeOfIdsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RangeOfIds</c>
	/// labeled alternative in <see cref="StaadParserParser.id_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangeOfIds([NotNull] StaadParserParser.RangeOfIdsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] StaadParserParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] StaadParserParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StaadParserParser.row_data_separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRow_data_separator([NotNull] StaadParserParser.Row_data_separatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StaadParserParser.row_data_separator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRow_data_separator([NotNull] StaadParserParser.Row_data_separatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LoadHeaderData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadHeaderData([NotNull] StaadParserParser.LoadHeaderDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LoadHeaderData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadHeaderData([NotNull] StaadParserParser.LoadHeaderDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntigerData([NotNull] StaadParserParser.IntigerDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntigerData([NotNull] StaadParserParser.IntigerDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleData([NotNull] StaadParserParser.DoubleDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleData([NotNull] StaadParserParser.DoubleDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextData([NotNull] StaadParserParser.TextDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="StaadParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextData([NotNull] StaadParserParser.TextDataContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
