//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SapParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISapParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SapParserBaseListener : ISapParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SapParserParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] SapParserParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SapParserParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] SapParserParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>programControlTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgramControlTable([NotNull] SapParserParser.ProgramControlTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>programControlTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgramControlTable([NotNull] SapParserParser.ProgramControlTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>pointsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointsTable([NotNull] SapParserParser.PointsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>pointsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointsTable([NotNull] SapParserParser.PointsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>areaElementsWithoutSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAreaElementsWithoutSectionsTable([NotNull] SapParserParser.AreaElementsWithoutSectionsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>areaElementsWithoutSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAreaElementsWithoutSectionsTable([NotNull] SapParserParser.AreaElementsWithoutSectionsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>areaSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAreaSectionsTable([NotNull] SapParserParser.AreaSectionsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>areaSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAreaSectionsTable([NotNull] SapParserParser.AreaSectionsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>areaSectionAssignmentsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAreaSectionAssignmentsTable([NotNull] SapParserParser.AreaSectionAssignmentsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>areaSectionAssignmentsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAreaSectionAssignmentsTable([NotNull] SapParserParser.AreaSectionAssignmentsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boundaryConditionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoundaryConditionsTable([NotNull] SapParserParser.BoundaryConditionsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boundaryConditionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoundaryConditionsTable([NotNull] SapParserParser.BoundaryConditionsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>materialsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterialsTable([NotNull] SapParserParser.MaterialsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>materialsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterialsTable([NotNull] SapParserParser.MaterialsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>materialsPropertiesTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaterialsPropertiesTable([NotNull] SapParserParser.MaterialsPropertiesTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>materialsPropertiesTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaterialsPropertiesTable([NotNull] SapParserParser.MaterialsPropertiesTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>activeDegressTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActiveDegressTable([NotNull] SapParserParser.ActiveDegressTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>activeDegressTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActiveDegressTable([NotNull] SapParserParser.ActiveDegressTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>frameSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameSectionsTable([NotNull] SapParserParser.FrameSectionsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>frameSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameSectionsTable([NotNull] SapParserParser.FrameSectionsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>frameElementsSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameElementsSectionsTable([NotNull] SapParserParser.FrameElementsSectionsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>frameElementsSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameElementsSectionsTable([NotNull] SapParserParser.FrameElementsSectionsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>frameElementsJointsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameElementsJointsTable([NotNull] SapParserParser.FrameElementsJointsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>frameElementsJointsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameElementsJointsTable([NotNull] SapParserParser.FrameElementsJointsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loadPatternsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadPatternsTable([NotNull] SapParserParser.LoadPatternsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loadPatternsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadPatternsTable([NotNull] SapParserParser.LoadPatternsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>pointsLoadsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointsLoadsTable([NotNull] SapParserParser.PointsLoadsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>pointsLoadsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointsLoadsTable([NotNull] SapParserParser.PointsLoadsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>frameLoadsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrameLoadsTable([NotNull] SapParserParser.FrameLoadsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>frameLoadsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrameLoadsTable([NotNull] SapParserParser.FrameLoadsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>areaLoadsUniformTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAreaLoadsUniformTable([NotNull] SapParserParser.AreaLoadsUniformTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>areaLoadsUniformTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAreaLoadsUniformTable([NotNull] SapParserParser.AreaLoadsUniformTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loadCaseTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadCaseTable([NotNull] SapParserParser.LoadCaseTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loadCaseTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadCaseTable([NotNull] SapParserParser.LoadCaseTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loadCaseAssignmentsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadCaseAssignmentsTable([NotNull] SapParserParser.LoadCaseAssignmentsTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loadCaseAssignmentsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadCaseAssignmentsTable([NotNull] SapParserParser.LoadCaseAssignmentsTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loadCombinationTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoadCombinationTable([NotNull] SapParserParser.LoadCombinationTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loadCombinationTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoadCombinationTable([NotNull] SapParserParser.LoadCombinationTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>otherTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOtherTable([NotNull] SapParserParser.OtherTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>otherTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOtherTable([NotNull] SapParserParser.OtherTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SapParserParser.table_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_content([NotNull] SapParserParser.Table_contentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SapParserParser.table_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_content([NotNull] SapParserParser.Table_contentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SapParserParser.table_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_row([NotNull] SapParserParser.Table_rowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SapParserParser.table_row"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_row([NotNull] SapParserParser.Table_rowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SapParserParser.table_row_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_row_item([NotNull] SapParserParser.Table_row_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SapParserParser.table_row_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_row_item([NotNull] SapParserParser.Table_row_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SapParserParser.table_footer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_footer([NotNull] SapParserParser.Table_footerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SapParserParser.table_footer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_footer([NotNull] SapParserParser.Table_footerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntigerData([NotNull] SapParserParser.IntigerDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntigerData([NotNull] SapParserParser.IntigerDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleData([NotNull] SapParserParser.DoubleDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleData([NotNull] SapParserParser.DoubleDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextData([NotNull] SapParserParser.TextDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextData([NotNull] SapParserParser.TextDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleQoutedTextData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleQoutedTextData([NotNull] SapParserParser.DoubleQoutedTextDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleQoutedTextData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleQoutedTextData([NotNull] SapParserParser.DoubleQoutedTextDataContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
