//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SapParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SapParserParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ISapParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SapParserParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] SapParserParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>programControlTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramControlTable([NotNull] SapParserParser.ProgramControlTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pointsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointsTable([NotNull] SapParserParser.PointsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>areaElementsWithoutSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAreaElementsWithoutSectionsTable([NotNull] SapParserParser.AreaElementsWithoutSectionsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>areaSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAreaSectionsTable([NotNull] SapParserParser.AreaSectionsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>areaSectionAssignmentsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAreaSectionAssignmentsTable([NotNull] SapParserParser.AreaSectionAssignmentsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boundaryConditionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoundaryConditionsTable([NotNull] SapParserParser.BoundaryConditionsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>materialsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterialsTable([NotNull] SapParserParser.MaterialsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>materialsPropertiesTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaterialsPropertiesTable([NotNull] SapParserParser.MaterialsPropertiesTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>activeDegressTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActiveDegressTable([NotNull] SapParserParser.ActiveDegressTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>frameSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrameSectionsTable([NotNull] SapParserParser.FrameSectionsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>frameElementsSectionsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrameElementsSectionsTable([NotNull] SapParserParser.FrameElementsSectionsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>frameElementsJointsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrameElementsJointsTable([NotNull] SapParserParser.FrameElementsJointsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loadPatternsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadPatternsTable([NotNull] SapParserParser.LoadPatternsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pointsLoadsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointsLoadsTable([NotNull] SapParserParser.PointsLoadsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>frameLoadsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrameLoadsTable([NotNull] SapParserParser.FrameLoadsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>areaLoadsUniformTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAreaLoadsUniformTable([NotNull] SapParserParser.AreaLoadsUniformTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loadCaseTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadCaseTable([NotNull] SapParserParser.LoadCaseTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loadCaseAssignmentsTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadCaseAssignmentsTable([NotNull] SapParserParser.LoadCaseAssignmentsTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loadCombinationTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadCombinationTable([NotNull] SapParserParser.LoadCombinationTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>otherTable</c>
	/// labeled alternative in <see cref="SapParserParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherTable([NotNull] SapParserParser.OtherTableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SapParserParser.table_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_content([NotNull] SapParserParser.Table_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SapParserParser.table_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_row([NotNull] SapParserParser.Table_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SapParserParser.table_row_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_row_item([NotNull] SapParserParser.Table_row_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SapParserParser.table_footer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_footer([NotNull] SapParserParser.Table_footerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntigerData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntigerData([NotNull] SapParserParser.IntigerDataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleData([NotNull] SapParserParser.DoubleDataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TextData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextData([NotNull] SapParserParser.TextDataContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleQoutedTextData</c>
	/// labeled alternative in <see cref="SapParserParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleQoutedTextData([NotNull] SapParserParser.DoubleQoutedTextDataContext context);
}
